const fs = require('fs');
const path = require('path');

const patterns = JSON.parse(fs.readFileSync('data/patterns.json', 'utf8'));
let narrative = {};
try { narrative = JSON.parse(fs.readFileSync('data/narrative.json', 'utf8')); } catch(e) {}
const verifLog = JSON.parse(fs.readFileSync('output/verification_log.json', 'utf8'));

const verifiedDir = 'data/verified';
const files = fs.readdirSync(verifiedDir).filter(f => f.endsWith('.json'));

let apps = [];
for (const file of files) {
  const content = JSON.parse(fs.readFileSync(path.join(verifiedDir, file), 'utf8'));
  apps.push(content);
}

// Ensure apps are sorted
apps.sort((a, b) => a.app_id.localeCompare(b.app_id));

// Helper for confident badge
const confidenceBadge = (conf) => {
  if (conf === 'agent_verified') return `<span class="badge badge-success">Agent Verified</span>`;
  if (conf === 'agent_only') return `<span class="badge badge-warning">Agent Only</span>`;
  if (conf === 'human_corrected') return `<span class="badge badge-danger">Human Corrected</span>`;
  return `<span class="badge badge-secondary">${conf || 'Unknown'}</span>`;
};

// Start building HTML
let html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Composio App Integration Research Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 1200px; margin: 0 auto; padding: 20px; }
        h1, h2, h3 { color: #2c3e50; }
        .section { margin-bottom: 40px; }
        .patterns { display: flex; flex-wrap: wrap; gap: 20px; }
        .pattern-card { background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 8px; padding: 20px; flex: 1; min-width: 300px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #dee2e6; }
        th { background-color: #f8f9fa; font-weight: 600; }
        tr:hover { background-color: #f1f3f5; }
        .badge { display: inline-block; padding: 0.25em 0.4em; font-size: 75%; font-weight: 700; line-height: 1; text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: 0.25rem; }
        .badge-success { color: #fff; background-color: #28a745; }
        .badge-warning { color: #212529; background-color: #ffc107; }
        .badge-danger { color: #fff; background-color: #dc3545; }
        .badge-secondary { color: #fff; background-color: #6c757d; }
        .badge-info { color: #fff; background-color: #17a2b8; }
        a { color: #007bff; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <h1>Composio App Integration Research Report</h1>
    
    <div class="section" id="headline-patterns">
        <h2>Headline Patterns</h2>
        <div class="patterns">
            <div class="pattern-card">
                <h3>Dominant Auth</h3>
                <p>OAuth2 dominates with ${patterns.auth_dominance.oauth2}% of apps, followed by API Key (${patterns.auth_dominance.api_key}%) and Token (${patterns.auth_dominance.token}%).</p>
            </div>
            <div class="pattern-card">
                <h3>Gated vs Self-Serve</h3>
                <p>${patterns.overall_access.self_serve}% of apps offer self-serve access, while ${patterns.overall_access.gated}% are gated.</p>
            </div>
            <div class="pattern-card">
                <h3>Common Blockers</h3>
                <ul>
                    ${Object.entries(patterns.common_blockers).slice(0,3).map(([k,v]) => `<li>${k}</li>`).join('')}
                </ul>
            </div>
            <div class="pattern-card">
                <h3>Easy Wins</h3>
                <p>${patterns.easy_wins.slice(0, 10).join(', ')} and ${patterns.easy_wins.length - 10} more...</p>
            </div>
        </div>
    </div>
    
    <div class="section" id="verification">
        <h2>Verification & Pipeline</h2>
        <p>This report was generated by an autonomous agent pipeline. <a href="https://github.com/cyb3rfy/composio-research" target="_blank">View the Repository</a> | <a href="https://github.com/cyb3rfy/composio-research/actions/workflows/pipeline.yml" target="_blank">Run the Pipeline Trigger</a></p>
        <p><strong>Verified on a stratified sample of 20/100 apps; pass-2 reflects post-correction accuracy on that sample, not a guarantee the other 80 are error-free.</strong></p>
        
        <h3>Defeated Apps</h3>
        <p>The following apps defeated the agent (required manual intervention or failed):</p>
        <ul>
            ${patterns.blocked_apps.map(app => `<li>${app}</li>`).join('')}
        </ul>
    </div>

    <div class="section" id="matrix">
        <h2>App Matrix</h2>
        <table>
            <thead>
                <tr>
                    <th>App Name</th>
                    <th>Category</th>
                    <th>Auth Methods</th>
                    <th>Access</th>
                    <th>Blockers</th>
                    <th>Confidence</th>
                    <th>Evidence</th>
                </tr>
            </thead>
            <tbody>`;

for (const app of apps) {
    const auth = app.auth_methods ? app.auth_methods.join(', ') : 'N/A';
    const access = app.access ? app.access.gate_type : 'N/A';
    const blockers = (app.buildability && app.buildability.blockers && app.buildability.blockers.length > 0) ? app.buildability.blockers.join('<br>') : 'None';
    
    // Extract first evidence URL if available
    let evidenceHtml = '-';
    if (app.evidence && app.evidence.length > 0) {
        // Just take the first one or create links for all? Let's just create a link for the first one, or maybe an icon per evidence
        const mainEvidence = app.evidence.find(e => e.evidence_url) || app.evidence[0];
        if (mainEvidence && mainEvidence.evidence_url) {
            evidenceHtml = \`<a href="\${mainEvidence.evidence_url}" target="_blank" title="\${mainEvidence.fact}">🔗 Link</a>\`;
        }
    }
    
    html += `
                <tr>
                    <td>\${app.app_name || app.app_id}</td>
                    <td>\${app.category || 'Unknown'}</td>
                    <td>\${auth}</td>
                    <td>\${access}</td>
                    <td>\${blockers}</td>
                    <td>\${confidenceBadge(app.confidence)}</td>
                    <td>\${evidenceHtml}</td>
                </tr>`;
}

html += `
            </tbody>
        </table>
    </div>
</body>
</html>`;

fs.writeFileSync('output/report.html', html);
console.log("Generated output/report.html successfully");
