import json, os, glob

# Load data
with open('data/patterns.json', 'r') as f:
    patterns = json.load(f)

try:
    with open('output/verification_log.json', 'r') as f:
        verif_log = json.load(f)
except:
    verif_log = []

# Load verified apps
app_files = glob.glob('data/verified/*.json')
apps = []
for file in app_files:
    with open(file, 'r') as f:
        apps.append(json.load(f))

apps.sort(key=lambda x: x.get('app_id', ''))

def confidence_badge(conf):
    if conf == 'agent_verified': return '<span class="badge badge-success">Agent Verified</span>'
    if conf == 'agent_only': return '<span class="badge badge-warning">Agent Only</span>'
    if conf == 'human_corrected': return '<span class="badge badge-danger">Human Corrected</span>'
    return f'<span class="badge badge-secondary">{conf or "Unknown"}</span>'

html_lines = [
    "<!DOCTYPE html>",
    "<html lang='en'>",
    "<head>",
    "    <meta charset='UTF-8'>",
    "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>",
    "    <title>Composio App Integration Research Report</title>",
    "    <style>",
    "        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 1200px; margin: 0 auto; padding: 20px; }",
    "        h1, h2, h3 { color: #2c3e50; }",
    "        .section { margin-bottom: 40px; }",
    "        .patterns { display: flex; flex-wrap: wrap; gap: 20px; }",
    "        .pattern-card { background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 8px; padding: 20px; flex: 1; min-width: 300px; }",
    "        table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 0.9em; }",
    "        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #dee2e6; }",
    "        th { background-color: #f8f9fa; font-weight: 600; }",
    "        tr:hover { background-color: #f1f3f5; }",
    "        .badge { display: inline-block; padding: 0.25em 0.4em; font-size: 75%; font-weight: 700; line-height: 1; text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: 0.25rem; }",
    "        .badge-success { color: #fff; background-color: #28a745; }",
    "        .badge-warning { color: #212529; background-color: #ffc107; }",
    "        .badge-danger { color: #fff; background-color: #dc3545; }",
    "        .badge-secondary { color: #fff; background-color: #6c757d; }",
    "        a { color: #007bff; text-decoration: none; }",
    "        a:hover { text-decoration: underline; }",
    "    </style>",
    "</head>",
    "<body>",
    "    <h1>Composio App Integration Research Report</h1>",
    "    ",
    "    <div class='section' id='headline-patterns'>",
    "        <h2>Headline Patterns</h2>",
    "        <div class='patterns'>",
    "            <div class='pattern-card'>",
    "                <h3>Dominant Auth</h3>",
    f"                <p>OAuth2 dominates with {patterns.get('auth_dominance', {}).get('oauth2', 0)} of apps, followed by API Key ({patterns.get('auth_dominance', {}).get('api_key', 0)}) and Token ({patterns.get('auth_dominance', {}).get('token', 0)}).</p>",
    "            </div>",
    "            <div class='pattern-card'>",
    "                <h3>Gated vs Self-Serve</h3>",
    f"                <p>{patterns.get('overall_access', {}).get('self_serve', 0)} of apps offer self-serve access, while {patterns.get('overall_access', {}).get('gated', 0)} are gated.</p>",
    "            </div>",
    "            <div class='pattern-card'>",
    "                <h3>Common Blockers</h3>",
    "                <ul>"
]

blockers = list(patterns.get('common_blockers', {}).items())[:3]
for b, count in blockers:
    html_lines.append(f"                    <li>{b}</li>")

html_lines.extend([
    "                </ul>",
    "            </div>",
    "            <div class='pattern-card'>",
    "                <h3>Easy Wins</h3>",
    f"                <p>{', '.join(patterns.get('easy_wins', [])[:10])} and {len(patterns.get('easy_wins', [])) - 10} more...</p>",
    "            </div>",
    "        </div>",
    "    </div>",
    "    ",
    "    <div class='section' id='verification'>",
    "        <h2>Verification & Pipeline</h2>",
    "        <p>This report was generated by an autonomous agent pipeline. <a href='https://github.com/cyb3rfy/composio-research' target='_blank'>View the Repository</a> | <a href='https://github.com/cyb3rfy/composio-research/actions/workflows/pipeline.yml' target='_blank'>Run the Pipeline Trigger</a></p>",
    "        <p><strong>Verified on a stratified sample of 20/100 apps; pass-2 reflects post-correction accuracy on that sample, not a guarantee the other 80 are error-free.</strong></p>",
    "        ",
    "        <h3>Verification Misses & Catches</h3>",
    "        <ul>"
])

for item in verif_log:
    app_id = item.get('app_id')
    mismatches = item.get('mismatches', 0)
    if mismatches > 0:
        details_list = []
        if 'diffs' in item:
            for d in item['diffs']:
                details_list.append(f"Field {d.get('field', 'unknown')} corrected from '{d.get('old', '')}' to '{d.get('new', '')}': {d.get('reason', '')}")
        if 'corrections' in item:
            for c in item['corrections']:
                details_list.append(f"Field {c.get('field', 'unknown')} corrected from '{c.get('old', '')}' to '{c.get('new', '')}': {c.get('reason', '')}")
        if 'details' in item:
            for k, v in item['details'].items():
                if 'mismatch' in str(v):
                    details_list.append(f"{k}: {v}")
        detail_str = "; ".join(details_list)
        html_lines.append(f"            <li><strong>{app_id}:</strong> {detail_str}</li>")

html_lines.extend([
    "        </ul>",
    "        ",
    "        <h3>Defeated Apps</h3>",
    "        <p>The following apps defeated the agent (required manual intervention or failed):</p>",
    "        <ul>"
])

for app in patterns.get('blocked_apps', []):
    html_lines.append(f"            <li>{app}</li>")

html_lines.extend([
    "        </ul>",
    "    </div>",
    "",
    "    <div class='section' id='matrix'>",
    "        <h2>App Matrix</h2>",
    "        <table>",
    "            <thead>",
    "                <tr>",
    "                    <th>App Name</th>",
    "                    <th>Category</th>",
    "                    <th>Auth Methods</th>",
    "                    <th>Access</th>",
    "                    <th>Blockers</th>",
    "                    <th>Confidence</th>",
    "                    <th>Evidence</th>",
    "                </tr>",
    "            </thead>",
    "            <tbody>"
])

for app in apps:
    name = app.get('app_name', app.get('app_id', 'Unknown'))
    cat = app.get('category', 'Unknown')
    
    auth_list = app.get('auth_methods', [])
    auth_strs = []
    for a in auth_list:
        if isinstance(a, dict):
            auth_strs.append(a.get('type', str(a)))
        else:
            auth_strs.append(str(a))
    auth = ', '.join(auth_strs) if auth_strs else 'N/A'
    
    access = 'N/A'
    if isinstance(app.get('access'), dict):
        access = app['access'].get('gate_type', 'N/A')
        
    blockers = 'None'
    if isinstance(app.get('buildability'), dict) and app['buildability'].get('blockers'):
        blockers = '<br>'.join(app['buildability']['blockers'])
        
    conf_badge = confidence_badge(app.get('confidence'))
    
    evidence_html = '-'
    evidence_list = app.get('evidence', [])
    for ev in evidence_list:
        if isinstance(ev, dict) and ev.get('evidence_url'):
            url = ev.get('evidence_url')
            evidence_html = f"<a href='{url}' target='_blank' title='Evidence Link'>🔗 Link</a>"
            break
            
    html_lines.append("                <tr>")
    html_lines.append(f"                    <td>{name}</td>")
    html_lines.append(f"                    <td>{cat}</td>")
    html_lines.append(f"                    <td>{auth}</td>")
    html_lines.append(f"                    <td>{access}</td>")
    html_lines.append(f"                    <td>{blockers}</td>")
    html_lines.append(f"                    <td>{conf_badge}</td>")
    html_lines.append(f"                    <td>{evidence_html}</td>")
    html_lines.append("                </tr>")

html_lines.extend([
    "            </tbody>",
    "        </table>",
    "    </div>",
    "</body>",
    "</html>"
])

with open('output/report.html', 'w') as f:
    f.write('\n'.join(html_lines))

print("Done")
